### ISSUE TITLE
Create a new Policy based on the Controller need

### ISSUE THREAD

**Issue by benyaminl** [rkusnadiii/dotnettask#11]
1. Admin
a. Semua Controller JWT
3. Author 
a. Hanya bisa akses PostController (sesuaikan dengan policynya)

For monday

**Comment by rkusnadiii** [comment]
![image](https://github.com/rkusnadiii/dotnettask/assets/51116850/a23eb044-e761-40b8-a2b5-22c5c14c6604)

**Comment by benyaminl** [comment]
Checked, but this using roles. nvm.
