### ISSUE TITLE
Edit Page is broken - No Query data passed

### ISSUE THREAD

**Issue by benyaminl** [rkusnadiii/dotnettask#4]
No Query data Passed
Error on viewing the update form 

![image](https://github.com/rkusnadiii/dotnettask/assets/2817332/e7a06569-dad3-41a5-b8ce-1bc698f9ffe7)

Pleas fix the code 
![image](https://github.com/rkusnadiii/dotnettask/assets/2817332/418cdbd0-67cf-41c0-8360-e1606a8cc67b)

**Comment by benyaminl** [comment]
This problem still occur... :'(

**Comment by benyaminl** [comment]
@rkusnadiii The Update page still blank... Please return the data on the forms so the user can edit it..

**Comment by rkusnadiii** [comment]
![image](https://github.com/rkusnadiii/dotnettask/assets/51116850/b70332a6-1a25-4b3e-a441-f9d2708325af)

Done
