### ISSUE TITLE
Request Filter hasn't instantiated, only added... 

### ISSUE THREAD

**Issue by benyaminl** [rkusnadiii/dotnettask#9]
On the CRUDController, there are no request filter that make the controller guarded, please check this.. 

re-read the material https://learn.microsoft.com/en-us/aspnet/core/mvc/controllers/filters?view=aspnetcore-7.0#built-in-filter-attributes

If you want to use what I taught you, you can reread the code, as it use different implementation as it derived from `IActionFilter` rather than `ActionFilterAttribute`. Choose what is simpler for you.

**Comment by rkusnadiii** [comment]
![image](https://github.com/rkusnadiii/dotnettask/assets/51116850/4de743e2-56b1-4abd-a0aa-2e283be472f2)

**Comment by benyaminl** [comment]
Filter implemented, but this return json, well.. minor..
